<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Select Street Name.....</name>
   <tag></tag>
   <elementGuidId>d224eec8-f578-45ab-98b9-f4c7f1f3236f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='SearchBox']/div[3]/div[2]/select</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>StreetName</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-options</name>
      <type>Main</type>
      <value>opt as opt.label for opt in streetNames</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-pristine ng-untouched ng-valid</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select Street Name.......10TH11TH121 ROW12TH12TH.13TH14TH15TH16TH17TH18TH19TH1ST20TH21ST22ND23RD24TH25TH2600 W. 26TH AVE.26TH27TH28TH29TH2ND30TH3131ST32ND33RD34TH35TH36TH37TH38TH39TH3RD40TH41ST42ND43RD44TH45TH46TH47TH48TH49TH4TH50TH51ST52ND53RD54TH54TH AVENUE55TH56TH57TH58TH59TH59TH NORTH59TH SOUTH5TH5TH AVENUE60TH61ST64TH6TH6TH AVE FRONTAGE71ST7TH8TH9THABILENEACADEMYACOMAADAADAKADAMSAIRPORTAKRONALABAMAALAMEDAALAMOALASKAALBIONALBROOKALCOTTALICEALTONALTURAALYSAMESAMHERSTAMMONSANAHEIMANDESANDREWSANNIEARAPAHOEARCHERARGONNEARGYLEARIZONAARKANSASARKINSASBURYASHASPENATCHISONATLANTICAUCKLANDAURARIAAVONDALEBAHAMABAILSBAKERBALDWINBALSAMBALTIMOREBANNOCKBARBERRYBARNETTBASSETTBATAVIABATESBAYAUDBEACHBEDFORDBEEKMANBEELERBELCAROBELLAIREBELLEVIEWBELLEWOODBELLWOODBENTONBERKELEYBERRYBETHANYBILLINGSBINGHAMBIRCHBISCAYBLACKHAWKBLAKEBOLLINGBONNIE BRAEBOSTONBOULDERBRENTWOODBRIGHTONBROADWAYBROWNBRUCE RANDOLPHBRYANTBRYONBUCHTELBUCKNELLBURLINGTONBYERSBYRONCAHITACAITHNESSCALIFORNIACANOSACAREYCARLANCARRCARSONCATHAYCEDARCENTERCENTRALCENTRAL PARKCEYLONCHAFFEECHAMBERSCHAMPACHANDLERCHASECHENANGOCHEROKEECHERRYCHERRY CR/CHERRYCHERRY CR/COLORADOCHERRY CR/HOLLYCHERRY CR/ILIFFCHERRY CR/MONACOCHERRY CR/QUEBECCHERRY CR/STEELECHERRY CR/UNIVERSITYCHERRY CREEK NORTHCHERRY CREEK SOUTHCHESTERCHESTNUTCHEYENNECHILDRENS MUSEUMCIRCLECITY PARK ESPLANADECLARKSONCLAUDECLAYCLAYTONCLEAR CREEKCLERMONTCLEVELANDCLINTONCLYDECOLFAXCOLFAX ACOLFAX BCOLGATECOLLEGECOLORADOCOLUMBIACOLUMBINECOLUMBUSCONEJOSCOOKCORNELLCORNISHCORONACOTTONWOODCOURTCOVECRESCENTCRESTLINECRESTMOORCROSSCROWNCRYSTALCURTISCUSTERD.T.C.DAHLIADAKOTADALEDALLASDANUBEDARTMOUTHDAVENPORTDAYTONDEARBORNDECATURDEEPHAVENDEER CREEK CANYONDEL RIODELAWAREDELGANYDENARGODENARGO MKTDENMARKDENNISONDENVERDEPEWDEPOTDETROITDEXTERDICK CONNORSDICKENSONDILLARDDILLONDIVISIONDIXIEDOANEDONALDDORADODOVERDOWNINGDTCDUDLEYDUKEDULUTHDUMASDUMBARTONDUNKELDDUNKIRKDURHAMEAGLEEASTMANEASTMOOREATONEDISONEDWARDSELATIELDORADOELGINELIOTELIZABETHELKELKHARTELLIPSEELLSWORTHELMELMENDORFELMIRAEMERSONEMPORIAENIDENSENADAERBERIEESPANAESTESEUCLIDEUDORAEUGENEEUREKAEVANSEVELYNEVERETTEXPOSITIONFAIRFAXFAIRMOUNTFAIRPLAYFAIRVIEWFEDERALFENTONFIELDFIFEFILBERTFILLMOREFIRTHFLAMINGOFLANDERSFLORAFLORENCEFLORIDAFLOWERFLOYDFONTANAFORDFORESTFOXFRANKFORTFRANKLINFRASERFREEPORTFRONTIERFRONTVIEW CRESCENTFULLERTONFULTONFUNDYGALAPAGOGALENAGARGARFIELDGARLANDGARRISONGATEWAYGAYLORDGENEVAGENOAGENOA STGIBRALTARGILLGILPINGINGERGIRARDGLENARMGLENCOEGLOBEVILLEGOLDENGOLFERSGRAMBLINGGRANBYGRANDGRANTGRANT RANCHGRAPEGRAYGREENGREEN MEADOWSGREENSBOROUGHGREENWOODGREGGGROVEGUNNISONHADDONHALEHALIFAXHAMILTONHAMPDENHANNIBALHANOVERHAPPY CANYONHARLANHARRISONHARVARDHARVEYHAVANAHAWTHORNEHAYWARDHAZELHELENAHENRYHIBISCUSHICKMANHIGHHIGHLAND PARKHIGHLINEHIGHLINE CANALHILLCRESTHILLSHILLSIDEHIMALAYAHOBARTHOLDENHOLLANDHOLLYHONEYHOOKERHOWARDHOYEHOYTHUDSONHUMBOLDTHURLEYHURONHURSTI-25I25/15TH AVEI25/19TH AVEI25/20TH STI25/23RD AVEI25/38TH AVEI25/44TH AVEI25/48TH AVEI25/6TH AVEI25/8TH AVEI25/ALAMEDA AVEI25/BELLEVIEW AVEI25/BROADWAYI25/BRYANT ON RAMPI25/COLFAX AVEI25/COLORADO BVI25/DOWNING STI25/EMERSON STI25/EVANS AVEI25/EXPRESS LANEI25/FRANKLIN STI25/HAMPDEN AVEI25/LOGAN STI25/LOUISIANA AVEI25/MOUSETRAPI25/SANTA FEI25/SPEER NORTHI25/SPEER SOUTHI25/STEELE STI25/WASHINGTON STI25/YALE AVEI70I70/FEDERALI70/LOWELLI70/PECOSI70/SHERIDANI70/TENNYSONI70/ZUNIIDAHOIDALIAILIFFINCAINDEPENDENCEINGALLSIOLAIOWAIRANIRELANDIRISIRONTONIRVINGIRVINGTONITHACAIVANIVANHOEIVYJACKSONJAMAICAJARVISJASMINEJASONJASPERJAVAJAYJEBELJEFFERSONJELLISONJERICHOJEROMEJERSEYJEWELLJOHNSONJOLIETJOPLINJOSEPHINEJOSLINJULIANKALAMATHKALISPELLKANSASKEARNEYKELLYKENDALLKENSINGKENTKENTONKENTUCKYKENYONKILLARNEYKINGKINGSTONKIPLINGKIRKKIRKWOODKITTREDGEKNOXKNOXVILLEKRAMERIALACKLANDLAFAYETTELAKERIDGELAMARLANGLEYLAREDOLARIMERLASALLELAWRENCELAYTONLEAFLEETSDALELEHIGHLEWISTONLEYDENLIMALINCOLNLINDENLINLEYLINVALELIPANLISBONLITTLE RAVENLIVERPOOLLOCUSTLOGANLOUISIANALOWELLLOWRYMABRYMACONMADISONMAGNOLIAMALAYAMALTAMANSFIELDMAPLEMAR VISTAMARCHMARIONMARIPOSAMARKETMARQUETTEMARSHALLMARTIN LUTHER KINGMARTINDALEMAXWELLMEADEMEDEAMEMPHISMERCERMEXICOMIAMIMICHIGANMILANMILWAUKEEMINNESOTAMISSISSIPPIMISSOURIMITCHELLMOLINEMONACOMONCRIEFFMONMOUTHMONROEMONTANAMONTCLAIRMONTVIEWMORRISONMORSEMOSIERMULBERRYMYRTLENAPANAPLESNARCISSUSNASSAUNATIONAL WESTERNNAVAJONAVARRONEBRASKANEILNEPALNETHERLANDNEVADANEW YORKNEWBERRYNEWLANDNEWPORTNEWTONNIAGARANIELSENNOMENORMANNORTHFIELDOAKOAKLANDOBERLINODESSAOGDENOHIOOHMOLEANDEROLIVEOLMSTEDONEIDAORANGEOREGONORLEANSOSAGEOSCEOLAOSWEGOOTISOXFORDPACIFICPACKING HOUSEPANORAMAPARISPARKPARKERPASEOPATTONPEACHPEARLPECOSPENNSYLVANIAPENSACOLAPEORIAPERRYPERTHPETERSONPIERCEPIMLICOPINEHURSTPINONPLATTEPLATTE RIVERPOLO CLUBPOLO FIELDPONTIACPOPLARPOTOMACPRAIRIE MEADOWPRENTICEPRINCETONPROGRESSQUANTUMQUARIQUAYQUEBECQUENTINQUIETOQUIGLEYQUINCEQUINCYQUINNQUITMANQUIVASRACERACINERADCLIFFRALEIGHRAMPARTRANDOLPHRARITANREADINGRED CROSSREEDREGISREVERERICERICHARD ALLENRICHTHOFENRINGSBYRIORIO GRANDERIVERROANOKEROBINSROCKMONTROSEMARYROSLYNRUTGERSSABLESAINT PAULSALEMSANDOWNSANTA ANITASANTA FESARATOGASAULSBURYscSCOTTSCRANTONSEBRINGSEMINOLESENECASEVERNSHANGRI LASHERIDANSHERMANSHORTSHOSHONESIDNEYSMITHSOUTHMOORSPEERSPEER/11TH AVESPEER/13TH AVESPEER/8TH AVESPEER/BANNOCK STSPEER/BROADWAYSPEER/CLARKSONSPEER/COLFAXSPEER/CORONASPEER/DOWNINGSPEER/GRANTSPEER/LOGANSPEER/WASHINGTONSPRUCEST PAULSTANFORDSTAPLETON NSTAPLETON SSTEAVENSONSTEELESTETSONSTOLLSTOUTSTREETSTUARTSUMACSUNSETSYRACUSETAMARACTANFORANTAOSTECHNOLOGYTEJONTELLERTELLURIDETEMPLETENNESSEETENNYSONTHOMPSONTHRILLTITANTOPEKATOWERTREMONTTRENTONTROYTRUCKEETUCSONTUFTSTULARETULSAUINTAULSTERUMATILLAUNIONUNIVERSITYUNOUPHAMUPTONURAVANURSULAUTAHUTICAUTOPIAUVALDAVALEVALENTIAVALLEJOVALLEYVANCEVASQUEZVASSARVAUGHNVENTURAVERBENAVICTORVILLANOVAVINCENNESVINEVIRGINIAVRAINWABASHWADSWORTHWAGONTRAILWALDENWALNUTWALSHWARNERWARRENWASHINGTONWATERWAXBERRYWAZEEWEBSTERWEIRWELLSWELTONWESLEYWESTWOODWEWATTAWHEELINGWHITINGWILDINGWILLIAMSWILLOWWILSONWINDSORWINONAWISTERIAWOLCOTTWOLFFWORCHESTERWYANDOTWYNKOOPWYOMINGXANADUXANTHIAXAPARYXAVIERXENIAXERICXINCAYALEYARNELLYATESYORKYOSEMITEYOSTYOUNGYUBAYUKONYUMAZENOBIAZIONZUNIZURICH</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;SearchBox&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-8&quot;]/select[@class=&quot;form-control ng-pristine ng-untouched ng-valid&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <value>//section[@id='SearchBox']/div[3]/div[2]/select</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Street Name:'])[1]/following::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Direction:'])[1]/following::select[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Qualifier:'])[1]/preceding::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search'])[1]/preceding::select[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <value>//div[3]/div[2]/select</value>
   </webElementXpaths>
</WebElementEntity>
